language: node_js
node_js:
- '0.10'
deploy:
  provider: npm
  email: dasrick@gmail.com
  api_key: 1591feec-12b3-420c-bcc5-b0ea7e11efc3
  on:
    tags: true
    repo: MovingImage24/mi-angular-bootstrap-ultron
